
---
title: "Report"
format: 
    docx:
        reference-doc: custom-reference.docx
execute:
    echo: false
---

## Results

In this section, we present the results of our analysis in response to the research questions outlined in the introduction.

RQ1. Do HMM and MSVAR identify economically distinct regimes when estimated on the same macro inputs? Do they agree on regime classifications, and are the regime-conditional moments interpretable as expansion and contraction?

RQ2. Does the autoregressive structure of the MSVAR produce more stable regime classifications than the HMM, i.e., fewer short-lived state assignments, lower allocation turnover, and less sensitivity to noisy macro observations?

RQ3. Does a macro-driven regime TAA strategy using either the HMM or the MSVAR deliver better risk-adjusted performance than well-known static benchmarks (60/40, equal-weight, buy-and-hold equity) after transaction costs over sampling period?

RQ4. Is the performance advantage, if any, of the MSVAR over the HMM consistent across sub-periods, including the 2020 COVID pandemic and the 2021–2022 inflation and rate-rise episode?


```{python}
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
```

### Classification of regimes according to HMM and MSVAR

Since the MSVAR loses one observation due to the autoregressive structure, we need to align the target weights of the MSVAR and HMM models for a fair comparison, i.e., starting from the second date for the hidden states uncovered by the HMM model.

First, let us look at the number of hidden states identified by each model. 

```{python}
hmm_weights = pd.read_csv("tables/hmm_target_weights.csv")
msvar_weights = pd.read_csv("tables/msvar_target_weights.csv")
hmm_regime_counts = hmm_weights.iloc[1:]['Regime'].value_counts()
msvar_regime_counts = msvar_weights['Regime'].value_counts()
```

```{python}
#| label: regime-counts-plot
#| fig-cap: "Number of hidden states identified by HMM and MSVAR"
#| fig-alt: "Bar plot comparing the number of hidden states identified by HMM and MSVAR"
regime_counts = pd.DataFrame({
    'HMM': hmm_regime_counts,
    'MSVAR': msvar_regime_counts
})
regime_counts.index = ["Expansion", "Contraction"]
regime_counts.plot(kind='bar', color=['gray', 'blue'], alpha=0.7)
# add counts on top of the bars
for i, v in enumerate(hmm_regime_counts):
    plt.text(i - 0.15, v + 2, str(v))
for i, v in enumerate(msvar_regime_counts):
    plt.text(i + 0.15, v + 2, str(v))
    
plt.xlabel('Regime')
plt.ylabel('Count')
plt.xticks(rotation=360, ha='center')
plt.show()
```

It is evident that the HMM identifies more recessionary months than the MSVAR, implying that the HMM is more sensitive to short-term fluctuations in the macroeconomic data, while the MSVAR captures more persistent regimes. This has implications for the turnover of the TAA strategy, as the HMM may lead to more frequent rebalancing due to its sensitivity to short-term changes in the macroeconomic environment. We will see later on that this is one of the reasons why the HMM-based TAA strategy underperforms the MSVAR-based strategy, as the higher turnover leads to higher transaction costs and lower risk-adjusted returns.

```{python}
# list dates where regime classifications differ between HMM and MSVAR
hmm_regimes = hmm_weights.iloc[1:]['Regime'].values
msvar_regimes = msvar_weights['Regime'].values
regime_diff_indices = np.where(hmm_regimes != msvar_regimes)[0]
```

```{python}
# create a dataframe to show the dates where regime classifications differ between HMM and MSVAR and the corresponding regimes
regime_diff_df = pd.DataFrame({
    'Date': hmm_weights.iloc[1:]['Date'].values[regime_diff_indices],
    'HMM': hmm_regimes[regime_diff_indices],
    'MSVAR': msvar_regimes[regime_diff_indices]
})
# replace 0 with "Expansion" and 1 with "Contraction" for better readability
regime_diff_df['HMM'] = regime_diff_df['HMM'].replace({0: 'Expansion', 1: 'Contraction'})
regime_diff_df['MSVAR'] = regime_diff_df['MSVAR'].replace({0: 'Expansion', 1: 'Contraction'})
```


```{python}
#| label: regime-diff-table
#| tbl-cap: "Dates where regime classifications differ between HMM and MSVAR." 
regime_diff_df
```

In total there are 20 months where the regime classifications differ between the two models, with the HMM identifying more contractionary months than the MSVAR. Eight of these months occur during the 2020 COVID pandemic, where the HMM identifies a normal regime while the MSVAR identifies a recessionary regime, which is more consistent with the economic conditions during that period. During the 2008 financial crisis, the HMM identifies more contractionary months than the MSVAR, which may be due to the HMM's sensitivity to short-term fluctuations in the macroeconomic data. 

### TAA strateies vs static benchmarks

We split the asset returns data into a training set (1990-2008) and a test set (2009-2025) to evaluate the out-of-sample performance of the TAA strategies based on the HMM and MSVAR models, as well as the static benchmarks (60/40, equal-weight, buy-and-hold equity).


```{python}
#| label: strategy-comparison-table
#| tbl-cap: "Performance metrics for TAA strategies based on HMM and MSVAR, as well as static benchmarks during the test period (2009-2025)"
strategy_comparison = pd.read_csv("tables/net_after_cost_strategy_comparison.csv")
strategy_comparison.rename(columns={'Unnamed: 0': 'Metric'}, inplace=True)
strategy_comparison.set_index('Metric', inplace=True) 
strategy_comparison.round(3)
```


```{python}
#| label: strategy-rankings-table
#| tbl-cap: "Net returns after transaction costs for TAA strategies based on HMM and MSVAR, as well as static benchmarks, ranked from highest (1) to lowest (5)."
strategy_rankings = pd.read_csv("tables/net_after_cost_strategy_ranking.csv")
strategy_rankings.rename(columns={'Unnamed: 0': 'Strategy'}, inplace=True)
strategy_rankings.set_index('Strategy', inplace=True)
ranking_columns = strategy_rankings.columns[-1:-5:-1]
strategy_rankings[ranking_columns]
```

Overall the MSVAR-based TAA strategy outperforms the HMM-based strategy on all the key performance metrics, including annualized return, volatility, Sharpe ratio, Sortino ratio and maximum drawdown. This supports our hypothesis that the autoregressive structure of the MSVAR model leads to more stable and perhaps more accurate regime classifications, leading to better risk-adjusted performance of the TAA strategy. 

The worst strategies are the buy-and-hold equity and the 60/40 static benchmark. In particular,the 60/40 benchmark performs worst in all the performance metrics, which is consistent with the findings in recent literature that the traditional 60/40 portfolio has underperformed in the low interest rate environment of the past decade. The buy-and-hold equity strategy has the highest annualized return, but also the highest volatility and maximum drawdown, leading to a lower Sharpe ratio and Sortino ratio compared to the MSVAR-based TAA strategy. 

Overall the equal-weight and the MSVAR-based TAA strategies are the top two strategies. The HMM-based TAA is ranked third, outperforming the buy-and-hold equity and the 60/40 benchmark, but still lagging behind the MSVAR-based TAA strategy.